version: '3'
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: messaging_platform
  web:
    image: messaging-platform
    ports:
      - '8080:8080'
    depends_on:
      - 'db'
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: ['./wait-for-it.sh', 'db:5432', '--', 'node', 'index.js']
networks:
  webnet:
